export default <Glasses.Item[]>[
  {
    brand: 'Maui Jim',
    sale: true,
    oldCoast: 385,
    model: 'Mavericks',
    coast: 255,
    id: '1',
    gender: 'all',
    sold: 453,
    isNew: false,
    lng: 4,
  },

  {
    brand: 'Ray-Ban',
    sale: false,
    oldCoast: 0,
    model: 'RB3447N Gold',
    coast: 145,
    id: '2',
    gender: 'man',
    sold: 523,
    isNew: true,
    lng: 4,
  },
  {
    brand: 'Ray-Ban',
    sale: true,
    oldCoast: 165,
    model: 'RB3539 Black',
    coast: 92,
    id: '3',
    gender: 'woman',
    sold: 152,
    isNew: true,
    lng: 4,
  },
  {
    brand: 'Ray-Ban',
    sale: true,
    oldCoast: 188,
    model: 'Sugar',
    coast: 138,
    id: '4',
    gender: 'all',
    sold: 43,
    isNew: false,
    lng: 4,
  },

  {
    brand: 'Oakley',
    sale: false,
    oldCoast: 0,
    model: 'Sutro',
    coast: 145,
    id: '5',
    gender: 'all',
    sold: 143,
    isNew: false,
    lng: 4,
  },
  {
    brand: 'Oakley',
    sale: false,
    oldCoast: 0,
    model: 'Evzero Path',
    coast: 139,
    id: '6',
    gender: 'all',
    sold: 343,
    isNew: true,
    lng: 4,
  },
  {
    brand: 'Oakley',
    sale: false,
    oldCoast: 0,
    model: 'Holbrook',
    coast: 139,
    id: '7',
    gender: 'all',
    sold: 243,
    isNew: true,
    lng: 4,
  },

  {
    brand: 'Prada',
    sale: false,
    oldCoast: 0,
    model: 'Cinema',
    coast: 253,
    id: '8',
    gender: 'all',
    sold: 743,
    isNew: false,
    lng: 3,
  },
  {
    brand: 'Prada',
    sale: false,
    oldCoast: 0,
    model: 'PR53US',
    coast: 117,
    id: '9',
    gender: 'woman',
    sold: 1343,
    isNew: true,
    lng: 2,
  },
  {
    brand: 'Prada',
    sale: false,
    oldCoast: 0,
    model: 'Millennials',
    coast: 109,
    id: '10',
    gender: 'all',
    sold: 103,
    isNew: true,
    lng: 4,
  },

  {
    brand: 'Levis',
    sale: true,
    oldCoast: 64,
    model: 'Tortoise',
    coast: 27,
    id: '11',
    gender: 'all',
    sold: 62,
    isNew: true,
    lng: 2,
  },
  {
    brand: 'Levis',
    sale: true,
    oldCoast: 40,
    model: 'LO22395 Red',
    coast: 20,
    id: '12',
    gender: 'all',
    sold: 482,
    isNew: false,
    lng: 2,
  },
  {
    brand: 'Levis',
    sale: true,
    oldCoast: 40,
    model: 'LO22393 Tortoise',
    coast: 20,
    id: '13',
    gender: 'woman',
    sold: 160,
    isNew: false,
    lng: 2,
  },

  {
    brand: 'Persol',
    sale: false,
    oldCoast: 0,
    model: 'PO3092SM Brown',
    coast: 170,
    id: '14',
    gender: 'all',
    sold: 60,
    isNew: false,
    lng: 4,
  },
  {
    brand: 'Persol',
    sale: false,
    oldCoast: 0,
    model: 'PO9714S',
    coast: 139,
    id: '15',
    gender: 'all',
    sold: 90,
    isNew: false,
    lng: 4,
  },

  {
    brand: 'Versace',
    sale: false,
    oldCoast: 0,
    model: 'VE2183',
    coast: 199,
    id: '16',
    gender: 'all',
    sold: 190,
    isNew: false,
    lng: 4,
  },
  {
    brand: 'Versace',
    sale: false,
    oldCoast: 0,
    model: 'VE2184',
    coast: 205,
    id: '17',
    gender: 'all',
    sold: 290,
    isNew: false,
    lng: 3,
  },

  {
    brand: 'Polaroid',
    sale: true,
    oldCoast: 80,
    model: 'PLD4138B',
    coast: 75,
    id: '18',
    gender: 'all',
    sold: 390,
    isNew: false,
    lng: 4,
  },
  {
    brand: 'Polaroid',
    sale: true,
    oldCoast: 90,
    model: 'PLD4139B',
    coast: 74,
    id: '19',
    gender: 'woman',
    sold: 50,
    isNew: false,
    lng: 3,
  },

  {
    brand: 'Saint Laurent',
    sale: true,
    oldCoast: 195,
    model: 'SL108 Fluo',
    coast: 95,
    id: '20',
    gender: 'woman',
    sold: 50,
    isNew: false,
    lng: 1,
  },
  {
    brand: 'Saint Laurent',
    sale: true,
    oldCoast: 550,
    model: 'SL302 LISA',
    coast: 420,
    id: '21',
    gender: 'woman',
    sold: 50,
    isNew: false,
    lng: 4,
  },

  {
    brand: 'Christian Dior',
    sale: true,
    oldCoast: 203,
    model: 'DIORCLUB1 Black',
    coast: 179,
    id: '22',
    gender: 'all',
    sold: 115,
    isNew: false,
    lng: 3,
  },
  {
    brand: 'Christian Dior',
    sale: true,
    oldCoast: 203,
    model: 'DiorSplit1 Split1',
    coast: 189,
    id: '23',
    gender: 'all',
    sold: 15,
    isNew: false,
    lng: 4,
  },
];
